Assignment # 1




In [2]:
import numpy as np

In [4]:
print(np.version)

<module 'numpy.version' from 'c:\\users\\pcplanet\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\numpy\\version.py'>


In [5]:
h=np.arange(11)

In [6]:
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.ones((3,3),dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
odd=h[h%2==1]

In [9]:
odd

array([1, 3, 5, 7, 9])

In [10]:
h[h%2==1]=-1

In [11]:
h

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [12]:
h=np.arange(11)

In [15]:
out=np.where(h%2==1,-1,h)

In [16]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [17]:
h

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [18]:
h=np.arange(10)

In [19]:
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
print(h.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
a=np.arange(10).reshape(2,-1)

In [22]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
b=np.repeat(1,10).reshape(2,-1)


In [25]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

creating numpy array of zeros

In [26]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 5 to 45

In [27]:
arr=np.arange(5,45)
print(arr)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]


finding shape of above array

In [28]:
print(arr.shape)

(40,)


printing the datatype of an array

In [29]:
print(arr.dtype)

int32


printing the version and configuration of numpy

In [30]:
print(np.__version__)


1.18.1


In [31]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [32]:
#printing dimensions
print(arr.ndim)

1


In [34]:
#Create a two dimensional array
td=np.full((2,3),4)
print(td)

[[4 4 4]
 [4 4 4]]


In [37]:
#printing a three dimensional array
t3d=np.full((2,2,2),3.4)
print(t3d)

[[[3.4 3.4]
  [3.4 3.4]]

 [[3.4 3.4]
  [3.4 3.4]]]


In [36]:
#reversing order of values in an array
p=np.arange(3,13)
print(p)
p=p[::-1]
print(p)

[ 3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3]


In [38]:
#Create a null vector of size 10 but the fifth value which is 1
u=np.zeros(10)
u[4]=1
print(u)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [39]:
#creating 3*3 identity matrix
ii=np.identity(3)
print(ii)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
#changing datatype from int to float
j=np.arange(5)
print(j)
j=j.astype("float64")
print(j)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]


In [42]:
#multiplying two arrays
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr1*arr2


array([[ 0,  8,  3],
       [28, 10, 72]])

In [48]:
#Make an array by comparing both the arrays provided above
f=np.array([0,1,2,3])
g=np.array([2,4,6,10])
o = g!=f
o

array([ True,  True,  True,  True])

In [49]:
#Extract all odd numbers from arr with values(0-9)
u=np.arange(0,10)
e=u[u%2==1]
e

array([1, 3, 5, 7, 9])

In [52]:
#Replace all odd numbers to -1 from previous array
u=np.arange(0,10)
u=np.where(u%2==1,-1,u)
u

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])